scara:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10
  trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    gains: # Required because we're controlling an effort interface
      joint1: {p: 300.0,  d: 20.0, i: 1, i_clamp: 0.01}
      joint2: {p: 300.0,  d: 20.0, i: 1, i_clamp: 0.01}
      joint3: {p: 300.0,  d: 20.0, i: 1, i_clamp: 0.01}
      joint4: {p: 300.0,  d: 20.0, i: 1, i_clamp: 0.01}
    allow_partial_joints_goal: True
