<?xml version="1.0" ?>

<robot name="robotiq_85_gripper" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties  -->
  <xacro:property name="height_from_floor" value="0.3"/>
  <xacro:property name="base_height" value="0.115"/>
  <xacro:property name="d1" value="0.87"/>
  <xacro:property name="a1" value="0.625"/>
  <xacro:property name="a2" value="0.425"/>
  <xacro:property name="l3" value="0.40"/>
  <xacro:property name="damping_value" value="1" />
  <xacro:property name="friction_value" value="1" />
  <material name="purple">
    <color rgba="0.252 0.246 .8 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <!-- Links  -->
  <link name="world"/>
  <link name="base_link">
     <visual>
        <geometry>
           <mesh filename="file://$(find scara-description)/urdf/base.dae"/>
        </geometry>
     </visual>
  </link>
  <link name="link1">
     <visual>
        <geometry>
           <mesh filename="file://$(find scara-description)/urdf/link1.dae"/>
        </geometry>
     </visual>
  </link>
  <link name="link2">
     <visual>
        <geometry>
           <mesh filename="file://$(find scara-description)/urdf/link2.dae"/>
        </geometry>
     </visual>
  </link>
  <link name="link3">
     <visual>
        <geometry>
           <mesh filename="file://$(find scara-description)/urdf/link3.dae"/>
        </geometry>
     </visual>
  </link>
  <link name="link4">
    <visual>
      <geometry>
         <mesh filename="file://$(find scara-description)/urdf/joint4.dae"/>
      </geometry>
    </visual>
  </link>
  <link name="tool">
    <visual>
      <geometry>
         <mesh filename="file://$(find scara-description)/urdf/link4.dae"/>
      </geometry>
    </visual>
  </link>

  <!-- Joints -->
  <joint name="fixed1" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${height_from_floor}" rpy="0 0 0"/>
  </joint>

  <joint name="fixed2" type="fixed">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
  </joint>

  <joint name="joint1" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${d1 - base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1" />
    <calibration rising="0.0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="30" velocity="1.0" lower="-3.14" upper="3.14" />
  </joint>

  <joint name="joint2" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="${a1} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1" />
    <calibration rising="0.0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="30" velocity="1.0" lower="-2.5" upper="2.5" />
  </joint>

  <joint name="joint3" type="revolute">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="${a2} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1" />
    <calibration rising="0.0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="30" velocity="1.0" lower="-2.5" upper="2.5" />
  </joint>

  <joint name="joint4" type="prismatic">
    <parent link="link4"/>
    <child link="tool"/>
    <origin xyz="0 0 -${l3}" rpy="3.14 0 0"/>
    <axis xyz="0 0 1" />
    <calibration rising="0.0"/>
    <dynamics damping="0.0" friction="0.0"/>
    <limit effort="30" velocity="1.0" lower="-0.2" upper="0.3" />
  </joint>

</robot>
